### ISSUE TITLE
Long bookmark name cut off

### ISSUE THREAD

**Issue by philip-s** [tborychowski/newtab-bookmarks#1]
Hello

Nice Firefox extension, does exactly what it schould. But I have the following problem: If the bookmark name gets wrapped, because it is too long for one line, it will be cut off (see in the image). I use Firefox 57.0.4 on Windows 7. 

Kind regards

![image](https://user-images.githubusercontent.com/14335447/34870445-5ec801e4-f78a-11e7-866b-714e6abcf4ed.png)

**Comment by tborychowski** [comment]
Thanks for that, I will look into this.
Unfortunately firefox doesn't support multiline ellipses, and setting a fixed height (even to 2em) seems to depend on the font-family (as it works for me on a mac).

**Comment by tborychowski** [comment]
Try version 1.0.2 it should work better. 
Please let me know if you still have issues :-)

**Comment by philip-s** [comment]
Yes it works! Great :)

2018-01-13 18:58 GMT+01:00 Tomasz Borychowski <notifications@github.com>:
