### ISSUE TITLE
Suggestion for UI / View 

### ISSUE THREAD

**Issue by rocketbee** [tborychowski/newtab-bookmarks#12]
First of all, a great addon. Great job. Searched a long time for a bookmark extension without cloud and registration. The user interface is clear and easy to understand. I have a suggestion for the presentation of the bookmarks. Besides the picture and the headline it would also be great if the description of the bookmarks could also be used. Would it be possible to make the view of the bookmarks similar to the "Brief" addon? 

Here is the link to the addon and the screenshots:   
https://addons.mozilla.org/de/firefox/addon/brief/

best regards

**Comment by tborychowski** [comment]
Thanks for the review and the feedback! :-)
I'm happy that you like it.
As for your suggestion - yes, I think that would be possible.
However:
1. This is not really something that I'd like to add, as it would increase the complexity, the maintenance and the memory needed by the cache, and decrease the performance. These descriptions are scraped from the websites, and for that I'd either have to create a separate proxy service (like for icons) or the extension would need to ask users for permission to access all visited websites (which - understandably - scares some people off) and the extension would send multiple requests (at least first time) as there are icons (performance hit).
2. Even if that was not a problem - unfortunately I don't have that much time any more for OS projects (personal reasons)...

Sorry if that disappoints you, but I hope you can understand my reasons :-)
