### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by h4p4t3** [tborychowski/newtab-bookmarks#13]
Hi there,

the installation of newtab-bookmarks fails since the update 4.0.0. 
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0

The browser-console gives the following output:

`Event received <unavailable>
amo-2e0246a2755697dd1c23.js:1:899256
item is null ext-chrome-settings-overrides.js:173
onManifestEntry
chrome://browser/content/parent/ext-chrome-settings-overrides.js:173:9
InterpretGeneratorResume self-hosted:1257:8 next self-hosted:1212:9
[GA: OFF] sendEvent {"hitType":"event","eventCategory":"AMO Addon Installs","eventAction":"addon","eventLabel":"newtab-bookmarks"} amo-2e0246a2755697dd1c23.js:1:899256
1540559986534	addons.xpi	WARN	Failed to install /tmp/tmp-hkx.xpi from https://addons.mozilla.org/firefox/downloads/file/1118214/newtab_bookmarks-4.0.0-fx.xpi?src=dp-btn-primary to /home/h4p4t3/.mozilla/firefox/xdcumwyi.default/extensions/staged/{63f66660-6017-4160-a378-4cea7e4beb99}.xpi: TypeError: item is null(chrome://browser/content/parent/ext-chrome-settings-overrides.js:173:9) JS Stack trace: onManifestEntry@ext-chrome-settings-overrides.js:173:9
[GA: OFF] Not logging to telemetry since hctEnabled: false amo-2e0246a2755697dd1c23.js:1:899256
Sending message that cannot be cloned. Are you trying to send an XPCOM object? addonManager.js:205:10
Event received <unavailable> amo-2e0246a2755697dd1c23.js:1:899256
TypeError: item is null[Weitere Informationen] ext-chrome-settings-overrides.js:173:9
Add-on found <unavailable> amo-2e0246a2755697dd1c23.js:1:899256
Error: 
Laden fehlgeschlagen für das <script> mit der Quelle "https://developer.mozilla.org/static/build/js/newsletter.a85c5c2892e5.js".`

**Comment by tborychowski** [comment]
thanks for that.
I disabled the last update (the fix I was trying to add there doesn't seem to work anyway).
Weird that this happens though...
It happened to me also, but I uninstalled the add-on and installed again (same one) and it worked...
Firefox is weird at times.
So many things annoyed me, that I switched to vivaldi since :-)

**Comment by h4p4t3** [comment]
So will you discontinue further development?

**Comment by tborychowski** [comment]
The  development is done. The add-on does what it says and does what I intended.
If there are any issues I will try to fix them, but I rather don't intent to add new features.
I know it's a common expectation that the software must  be updated every day and be in constant development to be cool, but I disagree with this.
I prefer software which is well defined, doesn't change much (nor often) and just works.
:-)

**Comment by h4p4t3** [comment]
That's fine for me. 

Just thought about the version 4.0. A major upgrade raises expectations. ;-)

I don't miss anything, so thank you for your development!

**Comment by tborychowski** [comment]
Your welcome.
And v4 was because it was a "breaking change" (setting homepage to the same as new-tab page).
So, according to semantic versioning - it's a major version change.
