### ISSUE TITLE
Blank page after recent update

### ISSUE THREAD

**Issue by newtabnotworking** [tborychowski/newtab-bookmarks#14]
Hi, I'm not the guy who left a review, but I saw his and have the same issue. After a recent update I have a blank new tab page instead of this addon's page. FF 63.0. Removing and reinstalling doesn't work, and I seem to have lost the ability to go to the addon's options page:

![tmp](https://user-images.githubusercontent.com/44656977/47826134-3b7b7600-dd4c-11e8-9f85-e280bb7606de.png)

After checking the Firefox version I noticed there was an update to 63.0.1. After updating I'm now getting this error: 

![tmp](https://user-images.githubusercontent.com/44656977/47826235-06bbee80-dd4d-11e8-8b5f-307727339cd8.png)

Removing and reinstalling the addon does not fix it. Thanks!

**Comment by tborychowski** [comment]
Hi,
Thanks a lot for this!
Which version of the addon do you have installed?
If you click on it - the addon page should show you the version, like this:
<img width="671" alt="screenshot 2018-11-01 at 08 42 18" src="https://user-images.githubusercontent.com/392513/47841610-1d486100-ddb2-11e8-8cac-642762be9fa0.png">

**Comment by thejdev** [comment]
Hi,

I'm having the same issue as @newtabnotworking. I am using Version 4.0.0:
![image](https://user-images.githubusercontent.com/1075854/47888265-21967c00-de8f-11e8-8ab2-09ffd7775be9.png)

Thanks!

JD

**Comment by tborychowski** [comment]
Guys, the latest version is 3.2.0.
<img width="473" alt="screenshot 2018-11-02 at 13 01 00" src="https://user-images.githubusercontent.com/392513/47916832-60343280-de9f-11e8-9802-71aaf3e3d527.png">

If you're using v4 than please uninstall and install the v3.2.0.
https://addons.mozilla.org/en-US/firefox/addon/newtab-bookmarks/versions/?page=1#version-3.2.0

I've published v4 by a mistake and deleted it almost immediately. 
I have no idea why firefox'es gallery keeps that cached!

Once you have the v3.2, please let me know if there's still a problem.

**Comment by newtabnotworking** [comment]
Looks like reverting to the old version fixed it for me.

**Comment by h4p4t3** [comment]
Hi there,

I've got the same problem with >= 3.3.0. Reverting to 3.2.0 and disabling upgrades works for me.

**Comment by tborychowski** [comment]
Hi @h4p4t3.
I've tested it just now thoroughly on my old Firefox, on a clean install of Firefox, on a Dev version of Firefox (on Mac and Linux) and all work fine with the latest v3.3.1 of the extension.
I don't have anything to work with here...
