### ISSUE TITLE
Local file links

### ISSUE THREAD

**Issue by h4p4t3** [tborychowski/newtab-bookmarks#15]
Hi there,

as I'm using TiddlyWiki I recently discovered that bookmarks pointing to local adresses (e.g. file:///home/h4p4t3/Downloads/tiddlywikilocations/TiddlyWiki.html won't open from the new-tab page. Is this limited because of security issues?

**Comment by tborychowski** [comment]
Yes, looks like a security issue: https://stackoverflow.com/questions/5317834/workaround-for-href-file-in-firefox#5338154

(I don't have local links in my bookmarks, so I have not encountered this issue before)

I don't see an easy workaround...

**Comment by h4p4t3** [comment]
Alright, no big deal. I'll get through it. ;-)
