### ISSUE TITLE
Privacy issue - URLs sent to external sites

### ISSUE THREAD

**Issue by junkblocker** [tborychowski/newtab-bookmarks#17]
It seems the addon makes calls to external services to generate icons and thumbnails with bookmark URLs. Had I not looked through the source code would have never noticed this. After praising the addon for #8 fix, this is a downer 😞

**Comment by tborychowski** [comment]
The icon generation script is on my private server and completely anonymous (as you can see in the source code](https://github.com/tborychowski/newtab-bookmarks/blob/master/src/js/index.js#L4).
I can share it if that helps your nerves 😄 
Unfortunately there is no other way to get these images...

**Comment by junkblocker** [comment]
Doesn't calm my nerves as that

1. Still leaks the URLs to you
2. Doesn't take care of the thumbnails version
3. This details that it sends the URLs elsewhere isn't mentioned anywhere till now

Solution wise one or more of these combined could work - 1) Reuse the icons that the browser itself may have cached? 2) Assume a favicon.ico or maybe load the URL once and get the icon url and cache that. 3) Do icon generation purely on the client side 4) Use identicons like https://blog.github.com/2013-08-14-identicons/ though that's not very useful. 5) Use the first letter of domain and color.

Not sure you'd think it is worth the effort but those are some suggestions.

**Comment by tborychowski** [comment]
Haha, the last thing in this world I care is someone else's bookmarks :-)
But I do understand your concerns very well (I like privacy).
Believe me, I spent days trying to figure out the least invasive way for this functionality.

Regarding the suggested solutions:
1. I'd love if the browser would expose them. But unfortunately it doesn't!
2. You'd be surprised how very few websites (at least from my pool) uses the old favicon.ico. As for loading the URL - unfortunately this is not possible from the extension either. It can only load URLs from servers which specifically allow CORS (cross-origin resource sharing), which 99% of normal websites don't do.
3. Same here - can't load URLs from servers without CORS enabled
4. This is a joke, right? :-) I'd rather see blank squares than these doodles.
5. This is the fallback, but it looks ugly as shit, so I'd prefer to avoid that.

I also don't understand your point about the thumbnails versions. Why would you care about versions here?

So here's what I'd suggest (and what cant be done):
- I will update the description to include the information about the 3rd party (that's an omission, and I agree that it should be there)
- I can update the config of the extension to allow for self-hosted thumbnail generation and will publish the server-side script (just 2 php files) for people who have servers and value privacy

**Comment by junkblocker** [comment]
> Haha, the last thing in this world I care is someone else's bookmarks :-)

Must be true if you say it :-)

> But I do understand your concerns very well (I like privacy).

That's not just privacy. That is security also.

> This is the fallback, but it looks ugly as shit, so I'd prefer to avoid that.

If you care to implement it, it doesn't need to be the default. This can be an option for people who prefer this for privacy reasons.

> I also don't understand your point about the thumbnails versions.

I meant the thumbnails option.

> I can update the config of the extension to allow for self-hosted thumbnail generation and will publish the server-side script (just 2 php files) for people who have servers and value privacy

Cheers for providing that option. I'll wait to see if you do 5 to restart using it. Otherwise if I end up feeling the need for an add-on like this bad, I'll just have to go implement it myself.

**Comment by tborychowski** [comment]
I will do that. However it won't be quick, as I don't have much time recently (nor am I using firefox anymore).

**Comment by tborychowski** [comment]
Hi!
I'm closing this issue as I don't plan to fix it here.
I'm working on a new extension that will be much better than this one (albeit not really compatible, hence a new project, instead of a new version).

In the new extension I'm planning to completely abandon any 3rd party services.
Icons/tiles will default to a letter + colour (or something simple like this) and allow to set a custom icon/image for each one.

Keep an eye on the new project here: https://github.com/tborychowski/perfect-home
