### ISSUE TITLE
feature request : sort by newest first

### ISSUE THREAD

**Issue by pi3141** [tborychowski/newtab-bookmarks#18]
Thanks for this good addon.
Would it be possible to add a sorting option, to display newest bookmark on the top of the grid ?
Thanks.

**Comment by tborychowski** [comment]
Hi,
Sorry, but this is against the design.
The whole idea of a  speed-dial is that you have a  fixed list of cards/bookmarks and  every one of them has its  own place (so to speak), so by using it - you learn and remember where everyone is.
Nest time the page loads your  mouse cursor is over the one you want even before the page finishes loading!
Adding this function would reorder the bookmarks every time you add a new one, so this whole idea goes to bin.
Honestly (and personally) I hate such solutions like "recent", "frequently used" and other dynamic sorting, as they remove the ability for the user to learn and get more "proficient" (faster) when using a piece of software.
It would also add more complexity and degrade  the performance (slightly, but still).
So sorry, but I won't implement that :-)
