### ISSUE TITLE
Add option to hide seperators

### ISSUE THREAD

**Issue by quassy** [tborychowski/newtab-bookmarks#20]
Instead of having seperators as empty spaces (current behaviour) or line breaks (see also #10), there should be an option to hide them alltogether. I like to use them in classic navigation but not for the newtab page.

**Comment by tborychowski** [comment]
Sorry, but this is a very specific to you only (so called edge case), for which I don't intend to adjust the whole addon.
I hope you can understand that if I would do that for every single request fro every person that uses this addon - it would quickly become a configuration monster full of bugs and other problems.
I want to keep it as simple as humanly possible, as fast as firefoxly possible and as minimalistic as possible.

**Comment by quassy** [comment]
I understand the general concern. But for me the current behaviour looked like a bug at first because separators are just displayed as empty spaces and those don't make much sense in a grid view.

So I guess what I'm actually proposing: Hide separators completely ;)

**Comment by tborychowski** [comment]
You should see that addition in v3.3.0!

**Comment by quassy** [comment]
```
.item.separator {
display:none;
}
```
Works as intended 👍
