### ISSUE TITLE
Can't use root folders

### ISSUE THREAD

**Issue by emptyother** [tborychowski/newtab-bookmarks#23]
**Probably a Firefox bug.** Cool extension, so i installed it on all my computers. But a weird bug: On my laptop I can't use any of the root folders as bookmarks. And if I leave it blank, it defaults to "Bokmerkemeny" (Bookmark menu), the first child in `browser.bookmarks.getTree(console.dir)`.

Running these commands on my laptop return an empty array, but running them on my work or home computer returns the correct item:
````
// Bookmark bar
browser.bookmarks.search({ title: 'Bokmerkelinje' }).then(console.dir);
// Bookmark meny
browser.bookmarks.search({ title: 'Bokmerkemeny' }).then(console.dir);
// Other bookmarks
browser.bookmarks.search({ title: 'Andre bokmerker' }).then(console.dir);
// Mobile bookmarks
browser.bookmarks.search({ title: 'Mobile bokmerker' }).then(console.dir);
````

But running the next command returns all of those above, in addition to every other bookmark, so they do exist.
````
browser.bookmarks.search({ title: '' }).then(console.dir);
// or
browser.bookmark.getTree(console.dir);
````

Any idea if a setting or something could cause this, before I try to reinstall firefox or report a firefox bug?

Firefox 69.0b9 (64-bit) Norwegian.
newtab-bookmarks v3.3.1

**Comment by tborychowski** [comment]
🤔 to be honest, I have no clue!
But it is very interesting :-)

If it gives you different results on different machines - than it looks like a bug (unless there's a setting that I don't know, or an antivirus which sets such a setting maybe?)
In any way - I will play around with these and if I can use the latter I will.

**Comment by tborychowski** [comment]
Hi!
I'm closing this issue as I don't plan to fix it here.
I'm working on a new extension that will be much better than this one (albeit not really compatible, hence a new project, instead of a new version).

This should be fixed in the new extension (when it's released).

Keep an eye on the new project here: https://github.com/tborychowski/perfect-home
