### ISSUE TITLE
Not reading Bookmarks Toolbar

### ISSUE THREAD

**Issue by excitive** [tborychowski/newtab-bookmarks#24]
On Firefox 69.0, 64 bit, Windows.
It is not reading "Bookmarks Toolbar" folder.
![newtab-bookmark-bug](https://user-images.githubusercontent.com/13506996/65131595-21f32380-da1d-11e9-958e-05fa6cbfa57a.png)

One more proof: If I put the root folder - "Bookmarks" - there also isn't a sub-folder named "Bookmarks Toolbar", so somehow Firefox has changed the access permissions?

**Comment by tborychowski** [comment]
Hi,

Ideally you should enter any folder name (that exists in your bookmarks) and it should pick it up.
However, it seems that newer versions of Firefox are more restrictive when returning the bookmarks list and don't include root folders anymore.

And now, the crux:
- Bad news is that this will not get fixed for this extension
- Good news is that I'm now working on a new extension that will work better, have more configurability and will not have that issue: https://github.com/tborychowski/perfect-home.
  I'm actively working on it, so shouldn't take too long (1 month max).
