### ISSUE TITLE
Keyboard Shortcut to return to main/previous folder

### ISSUE THREAD

**Issue by yijia-zhan** [tborychowski/newtab-bookmarks#6]
First thanks for making this! Immensely helpful for people who loves the speed of Firefox but misses the Opera speeddial style!

Just wondering if you have any plans of adding a shortcut, say `Esc`, to return to the main folder (or previous folder). Now once click into a folder, we'll need to hover the mouse cursor over the tiny `<` icon and click to be able to go back. It'd be a lot convenient if we can simply hit one key on the keyboard.

**Comment by tborychowski** [comment]
Hi @yijia-zhan,

Thanks for that :-)
You also have an option of using browser's (or, if you're mouse has them) back/forward buttons.
But I do like the speed of keyboard and am thinking about some keyboard support (as it's not difficult to do).

However, if I add `Esc` - it would rather go back to the parent folder than back all the way to the main folder :-)

**Comment by yijia-zhan** [comment]
Parent folder sounds good to me 👍. Again thanks for making this. I'll look into the code a bit and see if I can make some contributes : ).

**Comment by tborychowski** [comment]
btw. I'm planning to revamp the screenshotting/favicon generation, to make it independent on the 3rd party services.
The new extension api allows to hide the tabs so it might work nicely :-)

**Comment by tborychowski** [comment]
Hi!
I'm closing this issue as I don't plan to fix it here.
I'm working on a new extension that will be much better than this one (albeit not really compatible, hence a new project, instead of a new version).
Keep an eye on the new project here: https://github.com/tborychowski/perfect-home
