### ISSUE TITLE
Suddenly new permissions needed

### ISSUE THREAD

**Issue by junkblocker** [tborychowski/newtab-bookmarks#8]
One of the reasons I had picked this plugin was that it didn't require any horrible permissions.
With the latest update, it does.

- **Access your data for all website**
- **Access browser tabs**

 What gives?

**Comment by tborychowski** [comment]
Ha, good catch!
Actually I don't need that in its current state.
(I will remove it ASAP).

I added that as I was testing another solution for creating screenshots of pages (locally in the browser).
So the solution was like this:
- get URL of a bookmark
- open it in a new tab (`tabs` permission required)
- `captureTab` to create a screenshot ([requires `<all_urls>` permission](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/captureTab))

Anyways - this doesn't work that nicely, so for now I'm sticking to the current approach (using 3rd party service), so the permissions are not necessary.
(I forgot to remove them).

**Comment by tborychowski** [comment]
fixed in 2efe6b9287e5e41b6d099fb9c0b050380a70806a
will be available in the next release (2.0.1);

**Comment by tborychowski** [comment]
available now
https://addons.mozilla.org/en-US/firefox/addon/newtab-bookmarks/versions/?page=1#version-2.0.1

Thanks for reporting this!

**Comment by junkblocker** [comment]
Thanks for fixing it this fast!

> Actually I don't need that in its current state.

I think this is a distinguisher for your addon. If you do decide  to add the perms back in it will be a disincentive for me at least to using this addon over others.

Cheers
